apiVersion: v1
kind: Secret
metadata:
  name: ingress-whitelist
type: Opaque
data:
  list: TVM0eExqRXVNUT09
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acl-manager.konst.fish/list: ingress-whitelist
    acl-manager.konst.fish/type: secret
    acl-manager.konst.fish/destination: nginx.ingress.kubernetes.io/allowlist-source-range
  name: ingress-secret-list
  namespace: acl-manager
spec:
  ingressClassName: totally-real-ingress-class
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: nginx-service
            port:
              number: 80
        path: /
        pathType: Prefix